# Generated by Django 6.0.3 on 2026-03-04 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SellerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('api_token', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_id', models.BigIntegerField()),
                ('vendor_code', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.selleraccount')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srid', models.CharField(max_length=255, unique=True)),
                ('nm_id', models.BigIntegerField()),
                ('supplier_article', models.CharField(max_length=255)),
                ('tech_size', models.CharField(max_length=100)),
                ('warehouse_name', models.CharField(max_length=255)),
                ('warehouse_type', models.CharField(max_length=50)),
                ('region_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_cancel', models.BooleanField(default=False)),
                ('finished_price', models.FloatField(blank=True, null=True)),
                ('order_date', models.DateTimeField()),
                ('last_change_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.selleraccount')),
            ],
            options={
                'indexes': [models.Index(fields=['nm_id'], name='core_order_nm_id_1784bf_idx'), models.Index(fields=['warehouse_name'], name='core_order_warehou_593ab2_idx'), models.Index(fields=['region_name'], name='core_order_region__48ee4b_idx')],
            },
        ),
        migrations.CreateModel(
            name='WarehouseStockDetailed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_id', models.BigIntegerField()),
                ('supplier_article', models.CharField(max_length=255)),
                ('tech_size', models.CharField(max_length=100)),
                ('warehouse_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.selleraccount')),
            ],
            options={
                'indexes': [models.Index(fields=['nm_id'], name='core_wareho_nm_id_7d28e3_idx'), models.Index(fields=['warehouse_name'], name='core_wareho_warehou_15cd08_idx')],
            },
        ),
    ]
