# Generated by Django 6.0.3 on 2026-03-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='countryName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='oblastOkrugName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
