# Generated by Django 6.0.3 on 2026-03-04 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_wboffice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='countryName',
            new_name='country_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='oblastOkrugName',
            new_name='oblast_okrug_name',
        ),
    ]
