# Generated by Django 6.0.3 on 2026-03-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_countryname_order_country_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_local',
            field=models.BooleanField(default=False),
        ),
    ]
