# Generated by Django 6.0.3 on 2026-03-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_selleraccount_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='volume_liters',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_kg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
