# Generated by Django 6.0.3 on 2026-05-10 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_synctask_queue_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='consentlog',
            new_name='core_consen_email_e99e1b_idx',
            old_name='core_consen_email_f14989_idx',
        ),
        migrations.RenameIndex(
            model_name='consentlog',
            new_name='core_consen_user_id_7c1158_idx',
            old_name='core_consen_user_id_2f764a_idx',
        ),
        migrations.RenameIndex(
            model_name='consentlog',
            new_name='core_consen_kind_721abb_idx',
            old_name='core_consen_kind_697dd2_idx',
        ),
        migrations.RenameIndex(
            model_name='synctask',
            new_name='core_syncta_status_2a440c_idx',
            old_name='core_syncta_status_360e0f_idx',
        ),
        migrations.RenameIndex(
            model_name='synctask',
            new_name='core_syncta_seller__1e1f8d_idx',
            old_name='core_syncta_seller__574748_idx',
        ),
        migrations.RenameIndex(
            model_name='wbsalefact',
            new_name='core_wbsale_seller__f00933_idx',
            old_name='core_wbsale_seller__4a6ea6_idx',
        ),
        migrations.RenameIndex(
            model_name='wbsalefact',
            new_name='core_wbsale_seller__939b88_idx',
            old_name='core_wbsale_seller__6a6609_idx',
        ),
        migrations.RenameIndex(
            model_name='wbsalefact',
            new_name='core_wbsale_seller__c695ce_idx',
            old_name='core_wbsale_seller__cfdf95_idx',
        ),
    ]
