# Generated by Django 6.0.3 on 2026-03-11 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_product_volume_liters_product_weight_kg'),
    ]

    operations = [
        migrations.CreateModel(
            name='WbWarehouseTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_name', models.CharField(max_length=255)),
                ('tariff_date', models.DateField()),
                ('box_delivery_base', models.FloatField(blank=True, null=True)),
                ('box_delivery_liter', models.FloatField(blank=True, null=True)),
                ('box_delivery_marketplace_base', models.FloatField(blank=True, null=True)),
                ('box_delivery_marketplace_liter', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.selleraccount')),
            ],
            options={
                'indexes': [models.Index(fields=['seller', 'tariff_date'], name='core_wbware_seller__ac784c_idx'), models.Index(fields=['warehouse_name'], name='core_wbware_warehou_e656d7_idx')],
                'unique_together': {('seller', 'warehouse_name', 'tariff_date')},
            },
        ),
    ]
