# Generated by Django 6.0.3 on 2026-05-12 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_core_consen_email_f14989_idx_core_consen_email_e99e1b_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('price_discount', 'Скидка на тарифы'), ('free_days', 'Бесплатные дни')], max_length=32)),
                ('valid_until', models.DateTimeField()),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('discount_percent', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('applies_to_plan_codes', models.JSONField(blank=True, default=list)),
                ('free_days', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['kind', 'is_active', 'valid_until'], name='core_promoc_kind_feabe3_idx')],
            },
        ),
        migrations.CreateModel(
            name='PromoRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_code', models.CharField(blank=True, default='', max_length=20)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='core.promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['promo', 'created_at'], name='core_promor_promo_i_b2b2c7_idx'), models.Index(fields=['user', 'created_at'], name='core_promor_user_id_f472ec_idx')],
                'constraints': [models.UniqueConstraint(fields=('promo', 'user'), name='core_promoredemption_promo_user_uniq')],
            },
        ),
    ]
