# Generated by Django 6.0.3 on 2026-03-11 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_wbwarehousetariff'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransitDirectionTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transit_warehouse', models.CharField(max_length=255)),
                ('target_warehouse', models.CharField(blank=True, max_length=255, null=True)),
                ('target_region', models.CharField(blank=True, max_length=255, null=True)),
                ('tariff_per_pallet', models.FloatField(blank=True, null=True)),
                ('box_price_per_liter_lt_1500', models.FloatField(blank=True, null=True)),
                ('box_price_per_liter_gt_1500', models.FloatField(blank=True, null=True)),
                ('delivery_eta', models.CharField(blank=True, max_length=120, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.selleraccount')),
            ],
            options={
                'indexes': [models.Index(fields=['transit_warehouse'], name='core_transi_transit_7c624a_idx'), models.Index(fields=['target_region'], name='core_transi_target__8c9ee4_idx'), models.Index(fields=['seller'], name='core_transi_seller__60c039_idx')],
            },
        ),
    ]
