# Generated by Django 6.0.3 on 2026-05-12 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_promo_codes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('tbank', 'T-Bank')], default='tbank', max_length=20)),
                ('status', models.CharField(choices=[('created', 'Created'), ('init_failed', 'Init failed'), ('pending', 'Pending'), ('authorized', 'Authorized'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('canceled', 'Canceled')], default='created', max_length=20)),
                ('plan_code', models.CharField(choices=[('month_1', '1 месяц'), ('month_6', '6 месяцев'), ('month_12', '12 месяцев')], max_length=20)),
                ('order_id', models.CharField(max_length=36, unique=True)),
                ('provider_payment_id', models.CharField(blank=True, default='', max_length=64)),
                ('amount_rub', models.PositiveIntegerField(default=0)),
                ('amount_kopeks', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(blank=True, default='', max_length=140)),
                ('payment_url', models.URLField(blank=True, default='', max_length=1000)),
                ('promo_code', models.CharField(blank=True, default='', max_length=40)),
                ('promo_snapshot', models.JSONField(blank=True, default=dict)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('notification_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notification_received_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='core.promocode')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='core.usersubscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='core_billin_user_id_3961da_idx'), models.Index(fields=['status', 'created_at'], name='core_billin_status_706294_idx'), models.Index(fields=['provider', 'provider_payment_id'], name='core_billin_provide_ecb6d6_idx')],
            },
        ),
    ]
