# Generated by Django 6.0.3 on 2026-03-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_transitdirectiontariff'),
    ]

    operations = [
        migrations.AddField(
            model_name='wbwarehousetariff',
            name='box_delivery_coef_expr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wbwarehousetariff',
            name='box_delivery_marketplace_coef_expr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wbwarehousetariff',
            name='box_storage_base',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wbwarehousetariff',
            name='box_storage_coef_expr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wbwarehousetariff',
            name='box_storage_liter',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wbwarehousetariff',
            name='geo_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
