# Generated by Django 6.0.3 on 2026-03-12 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_wbwarehousetariff_box_delivery_coef_expr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealizationReportDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rrd_id', models.BigIntegerField()),
                ('realizationreport_id', models.BigIntegerField(blank=True, null=True)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('create_dt', models.DateField(blank=True, null=True)),
                ('srid', models.CharField(blank=True, max_length=255, null=True)),
                ('nm_id', models.BigIntegerField(blank=True, null=True)),
                ('sa_name', models.CharField(blank=True, max_length=255, null=True)),
                ('office_name', models.CharField(blank=True, max_length=255, null=True)),
                ('site_country', models.CharField(blank=True, max_length=255, null=True)),
                ('bonus_type_name', models.CharField(blank=True, max_length=255, null=True)),
                ('supplier_oper_name', models.CharField(blank=True, max_length=255, null=True)),
                ('doc_type_name', models.CharField(blank=True, max_length=120, null=True)),
                ('order_dt', models.DateTimeField(blank=True, null=True)),
                ('sale_dt', models.DateTimeField(blank=True, null=True)),
                ('rr_dt', models.DateField(blank=True, null=True)),
                ('fix_tariff_date_from', models.DateField(blank=True, null=True)),
                ('fix_tariff_date_to', models.DateField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('delivery_rub', models.FloatField(blank=True, null=True)),
                ('dlv_prc', models.FloatField(blank=True, null=True)),
                ('storage_fee', models.FloatField(blank=True, null=True)),
                ('deduction', models.FloatField(blank=True, null=True)),
                ('acceptance', models.FloatField(blank=True, null=True)),
                ('rebill_logistic_cost', models.FloatField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.selleraccount')),
            ],
            options={
                'indexes': [models.Index(fields=['seller', 'rr_dt'], name='core_realiz_seller__f86c4b_idx'), models.Index(fields=['seller', 'srid'], name='core_realiz_seller__f98ad6_idx'), models.Index(fields=['seller', 'office_name'], name='core_realiz_seller__0d4f3f_idx')],
                'unique_together': {('seller', 'rrd_id')},
            },
        ),
    ]
