# Generated by Django 6.0.3 on 2026-09-06 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_price_robot'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_id', models.BigIntegerField()),
                ('vendor_code', models.CharField(blank=True, default='', max_length=255)),
                ('old_price', models.FloatField(blank=True, null=True)),
                ('new_price', models.FloatField(blank=True, null=True)),
                ('old_discount', models.FloatField(blank=True, null=True)),
                ('new_discount', models.FloatField(blank=True, null=True)),
                ('old_net', models.FloatField(blank=True, null=True)),
                ('new_net', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(choices=[('robot', 'Ценовой робот'), ('manual', 'Вручную')], default='robot', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_changes', to='core.pricerobotrun')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_changes', to='core.selleraccount')),
            ],
            options={
                'indexes': [models.Index(fields=['seller', 'nm_id', 'created_at'], name='core_pricec_seller__675606_idx'), models.Index(fields=['seller', 'created_at'], name='core_pricec_seller__2f7f69_idx')],
            },
        ),
    ]
