# Generated by Django 6.0.3 on 2026-03-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_wbacceptancecoefficient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='srid',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('seller', 'srid')},
        ),
    ]
