# Generated by Django 6.0.3 on 2026-03-20 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_core_wbacce_seller__fab4f0_idx_core_wbacce_seller__260374_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('error', 'Error')], default='running', max_length=20)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('step', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, default='')),
                ('result', models.JSONField(blank=True, default=dict)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='synctask',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.selleraccount'),
        ),
        migrations.AddField(
            model_name='synctask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='synctask',
            index=models.Index(fields=['user', 'created_at'], name='core_syncta_user_id_868a33_idx'),
        ),
        migrations.AddIndex(
            model_name='synctask',
            index=models.Index(fields=['task_id'], name='core_syncta_task_id_a5509c_idx'),
        ),
    ]
