# Generated by Django 6.0.3 on 2026-03-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_synctask_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KtrTableVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=120)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('ktr_ranges', models.JSONField(blank=True, default=list)),
                ('min_orders_threshold', models.PositiveIntegerField(default=1000)),
                ('source_label', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogisticsRuleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=120)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('small_volume_tiers', models.JSONField(blank=True, default=list)),
                ('large_volume_first_liter_cost', models.FloatField(default=46.0)),
                ('large_volume_additional_liter_cost', models.FloatField(default=14.0)),
                ('source_label', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='wbacceptancecoefficient',
            new_name='core_wbacce_seller__260374_idx',
            old_name='core_wbacce_seller__fab4f0_idx',
        ),
        migrations.RenameIndex(
            model_name='wbacceptancecoefficient',
            new_name='core_wbacce_warehou_9898db_idx',
            old_name='core_wbacce_warehou_a18850_idx',
        ),
        migrations.RenameIndex(
            model_name='wbacceptancecoefficient',
            new_name='core_wbacce_warehou_b68989_idx',
            old_name='core_wbacce_warehou_3fd925_idx',
        ),
        migrations.RenameIndex(
            model_name='wbacceptancecoefficient',
            new_name='core_wbacce_box_typ_a423f8_idx',
            old_name='core_wbacce_box_typ_5a0fe4_idx',
        ),
        migrations.AddIndex(
            model_name='ktrtableversion',
            index=models.Index(fields=['date_from', 'date_to'], name='core_ktrtab_date_fr_2ee3d4_idx'),
        ),
        migrations.AddIndex(
            model_name='ktrtableversion',
            index=models.Index(fields=['is_active'], name='core_ktrtab_is_acti_6b2792_idx'),
        ),
        migrations.AddConstraint(
            model_name='ktrtableversion',
            constraint=models.CheckConstraint(condition=models.Q(('date_from__lte', models.F('date_to'))), name='ktr_table_date_from_lte_date_to'),
        ),
        migrations.AddIndex(
            model_name='logisticsruleversion',
            index=models.Index(fields=['date_from', 'date_to'], name='core_logist_date_fr_3cedff_idx'),
        ),
        migrations.AddIndex(
            model_name='logisticsruleversion',
            index=models.Index(fields=['is_active'], name='core_logist_is_acti_b723a1_idx'),
        ),
        migrations.AddConstraint(
            model_name='logisticsruleversion',
            constraint=models.CheckConstraint(condition=models.Q(('date_from__lte', models.F('date_to'))), name='log_rule_date_from_lte_date_to'),
        ),
    ]
