# Generated by Django 6.0.3 on 2026-03-20 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_ktrtableversion_logisticsruleversion_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ktrtableversion',
            name='core_ktrtab_date_fr_2ee3d4_idx',
        ),
        migrations.RemoveIndex(
            model_name='ktrtableversion',
            name='core_ktrtab_is_acti_6b2792_idx',
        ),
        migrations.RemoveConstraint(
            model_name='ktrtableversion',
            name='ktr_table_date_from_lte_date_to',
        ),
        migrations.DeleteModel(
            name='KtrTableVersion',
        ),
        migrations.RemoveIndex(
            model_name='logisticsruleversion',
            name='core_logist_date_fr_3cedff_idx',
        ),
        migrations.RemoveIndex(
            model_name='logisticsruleversion',
            name='core_logist_is_acti_b723a1_idx',
        ),
        migrations.RemoveConstraint(
            model_name='logisticsruleversion',
            name='log_rule_date_from_lte_date_to',
        ),
        migrations.DeleteModel(
            name='LogisticsRuleVersion',
        ),
    ]
