# Generated by Django 6.0.3 on 2026-03-22 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_synctask_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=120)),
                ('level', models.CharField(choices=[('error', 'Error'), ('warning', 'Warning'), ('info', 'Info')], default='error', max_length=20)),
                ('message', models.TextField()),
                ('path', models.CharField(blank=True, default='', max_length=500)),
                ('traceback_text', models.TextField(blank=True, default='')),
                ('context_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.selleraccount')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['source', 'created_at'], name='core_apperr_source_b63806_idx'), models.Index(fields=['level', 'created_at'], name='core_apperr_level_6fc291_idx'), models.Index(fields=['user', 'created_at'], name='core_apperr_user_id_2735a1_idx')],
            },
        ),
        migrations.CreateModel(
            name='TesterFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.CharField(blank=True, default='', max_length=500)),
                ('category', models.CharField(choices=[('bug', 'Баг интерфейса'), ('calc', 'Неточность расчета'), ('sync', 'Проблема синхронизации'), ('idea', 'Идея/улучшение')], default='bug', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='medium', max_length=20)),
                ('message', models.TextField()),
                ('include_context', models.BooleanField(default=True)),
                ('context_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('fixed', 'Исправлено'), ('wontfix', 'Не планируется')], default='new', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.selleraccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='core_tester_status_f10996_idx'), models.Index(fields=['category', 'priority'], name='core_tester_categor_7c7327_idx'), models.Index(fields=['user', 'created_at'], name='core_tester_user_id_76e6fa_idx')],
            },
        ),
    ]
