# Generated by Django 6.0.3 on 2026-04-15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_remove_ktrtableversion_core_ktrtab_date_fr_2ee3d4_idx_and_more"),
        ("core", "0017_apperrorlog_testerfeedback"),
    ]

    operations = []

