# Generated by Django 6.0.3 on 2026-04-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_merge_0016_0017"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="photo_url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="title",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]

