# Generated by Django 6.0.3 on 2026-04-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_product_title_photo_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="wb_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="wb_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]

