# Generated by Django 6.0.3 on 2026-04-17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_product_wb_created_at_product_wb_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="SellerWarehouse",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("seller_warehouse_id", models.BigIntegerField()),
                ("office_id", models.BigIntegerField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("cargo_type", models.IntegerField(blank=True, null=True)),
                ("delivery_type", models.IntegerField(blank=True, null=True)),
                ("is_deleting", models.BooleanField(default=False)),
                ("is_processing", models.BooleanField(default=False)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("seller", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.selleraccount")),
            ],
            options={
                "unique_together": {("seller", "seller_warehouse_id")},
            },
        ),
        migrations.AddIndex(
            model_name="sellerwarehouse",
            index=models.Index(fields=["seller", "name"], name="core_sellerw_seller__b446af_idx"),
        ),
        migrations.AddIndex(
            model_name="sellerwarehouse",
            index=models.Index(fields=["seller", "office_id"], name="core_sellerw_seller__c0d227_idx"),
        ),
        migrations.AddIndex(
            model_name="sellerwarehouse",
            index=models.Index(fields=["seller", "updated_at"], name="core_sellerw_seller__8e863d_idx"),
        ),
    ]

