# Generated by Django 6.0.3 on 2026-04-17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_sellerwarehouse"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCardSize",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("chrt_id", models.BigIntegerField()),
                ("nm_id", models.BigIntegerField(blank=True, null=True)),
                ("vendor_code", models.CharField(blank=True, max_length=255, null=True)),
                ("title", models.CharField(blank=True, max_length=500, null=True)),
                ("tech_size", models.CharField(blank=True, max_length=100, null=True)),
                ("wb_size", models.CharField(blank=True, max_length=100, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("seller", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.selleraccount")),
            ],
            options={
                "unique_together": {("seller", "chrt_id")},
            },
        ),
        migrations.CreateModel(
            name="SellerFbsStock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("warehouse_name", models.CharField(max_length=255)),
                ("chrt_id", models.BigIntegerField()),
                ("amount", models.IntegerField(default=0)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("seller", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.selleraccount")),
                ("seller_warehouse", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.sellerwarehouse")),
            ],
            options={
                "unique_together": {("seller", "seller_warehouse", "chrt_id")},
            },
        ),
        migrations.AddIndex(
            model_name="productcardsize",
            index=models.Index(fields=["seller", "vendor_code"], name="core_produc_seller__14f4e7_idx"),
        ),
        migrations.AddIndex(
            model_name="productcardsize",
            index=models.Index(fields=["seller", "nm_id"], name="core_produc_seller__a1f856_idx"),
        ),
        migrations.AddIndex(
            model_name="sellerfbsstock",
            index=models.Index(fields=["seller", "warehouse_name"], name="core_sellerf_seller__7f86e2_idx"),
        ),
        migrations.AddIndex(
            model_name="sellerfbsstock",
            index=models.Index(fields=["seller", "chrt_id"], name="core_sellerf_seller__0c0cc1_idx"),
        ),
        migrations.AddIndex(
            model_name="sellerfbsstock",
            index=models.Index(fields=["seller", "updated_at"], name="core_sellerf_seller__cca0b0_idx"),
        ),
    ]

