# Generated by Django 6.0.3 on 2026-04-17 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_uniteconomicssettings_acquiring_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductUnitEconomicsCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.JSONField(blank=True, default=dict)),
                ('result_data', models.JSONField(blank=True, default=dict)),
                ('net_profit', models.FloatField(default=0.0)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='productuniteconomicscalculation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
        migrations.AddField(
            model_name='productuniteconomicscalculation',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.selleraccount'),
        ),
        migrations.AddIndex(
            model_name='productuniteconomicscalculation',
            index=models.Index(fields=['seller', 'product'], name='core_produc_seller__895d0a_idx'),
        ),
        migrations.AddIndex(
            model_name='productuniteconomicscalculation',
            index=models.Index(fields=['seller', 'calculated_at'], name='core_produc_seller__c4d906_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productuniteconomicscalculation',
            unique_together={('seller', 'product')},
        ),
    ]
