# Generated by Django 6.0.3 on 2026-04-17 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_productuniteconomicscalculation_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='productcardsize',
            new_name='core_produc_seller__59e363_idx',
            old_name='core_produc_seller__14f4e7_idx',
        ),
        migrations.RenameIndex(
            model_name='productcardsize',
            new_name='core_produc_seller__1abb65_idx',
            old_name='core_produc_seller__a1f856_idx',
        ),
        migrations.RenameIndex(
            model_name='productsizeprice',
            new_name='core_produc_seller__083edb_idx',
            old_name='core_produc_seller__6d3838_idx',
        ),
        migrations.RenameIndex(
            model_name='productsizeprice',
            new_name='core_produc_seller__bda71c_idx',
            old_name='core_produc_seller__988218_idx',
        ),
        migrations.RenameIndex(
            model_name='productsizeprice',
            new_name='core_produc_seller__6f5386_idx',
            old_name='core_produc_seller__396f3c_idx',
        ),
        migrations.RenameIndex(
            model_name='sellerfbsstock',
            new_name='core_seller_seller__de2454_idx',
            old_name='core_sellerf_seller__7f86e2_idx',
        ),
        migrations.RenameIndex(
            model_name='sellerfbsstock',
            new_name='core_seller_seller__48a2d4_idx',
            old_name='core_sellerf_seller__0c0cc1_idx',
        ),
        migrations.RenameIndex(
            model_name='sellerfbsstock',
            new_name='core_seller_seller__71e86d_idx',
            old_name='core_sellerf_seller__cca0b0_idx',
        ),
        migrations.RenameIndex(
            model_name='sellerwarehouse',
            new_name='core_seller_seller__fa9145_idx',
            old_name='core_sellerw_seller__b446af_idx',
        ),
        migrations.RenameIndex(
            model_name='sellerwarehouse',
            new_name='core_seller_seller__729f87_idx',
            old_name='core_sellerw_seller__c0d227_idx',
        ),
        migrations.RenameIndex(
            model_name='sellerwarehouse',
            new_name='core_seller_seller__504869_idx',
            old_name='core_sellerw_seller__8e863d_idx',
        ),
        migrations.RenameIndex(
            model_name='wbcategorycommission',
            new_name='core_wbcate_seller__a83096_idx',
            old_name='core_wbcatc_seller__0d08cc_idx',
        ),
        migrations.RenameIndex(
            model_name='wbcategorycommission',
            new_name='core_wbcate_seller__2956b7_idx',
            old_name='core_wbcatc_seller__6c79a9_idx',
        ),
    ]
