# Generated by Django 6.0.3 on 2026-04-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_rename_core_produc_seller__14f4e7_idx_core_produc_seller__59e363_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniteconomicssettings',
            name='acceptance_cost_per_liter',
            field=models.FloatField(default=1.7),
        ),
    ]
