# Generated by Django 6.0.3 on 2026-04-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_uniteconomicssettings_acceptance_cost_per_liter'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
