# Generated by Django 6.0.3 on 2026-04-19 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_product_purchase_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='WbAdvertCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advert_id', models.BigIntegerField()),
                ('campaign_name', models.CharField(blank=True, max_length=500, null=True)),
                ('advert_type', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('change_time', models.DateTimeField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('daily_budget', models.FloatField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.selleraccount')),
            ],
            options={
                'indexes': [models.Index(fields=['seller', 'advert_id'], name='core_wbadve_seller__c7a2a9_idx'), models.Index(fields=['seller', 'status'], name='core_wbadve_seller__f7f0eb_idx'), models.Index(fields=['seller', 'updated_at'], name='core_wbadve_seller__56c728_idx')],
                'unique_together': {('seller', 'advert_id')},
            },
        ),
        migrations.CreateModel(
            name='WbAdvertStatDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advert_id', models.BigIntegerField()),
                ('stat_date', models.DateField()),
                ('nm_id', models.BigIntegerField(blank=True, null=True)),
                ('spend', models.FloatField(default=0.0)),
                ('views', models.IntegerField(blank=True, null=True)),
                ('clicks', models.IntegerField(blank=True, null=True)),
                ('orders', models.IntegerField(blank=True, null=True)),
                ('add_to_cart', models.IntegerField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.selleraccount')),
            ],
            options={
                'indexes': [models.Index(fields=['seller', 'stat_date'], name='core_wbadve_seller__e7bb02_idx'), models.Index(fields=['seller', 'nm_id', 'stat_date'], name='core_wbadve_seller__39c473_idx'), models.Index(fields=['seller', 'advert_id', 'stat_date'], name='core_wbadve_seller__57a2cf_idx')],
                'unique_together': {('seller', 'advert_id', 'stat_date', 'nm_id')},
            },
        ),
    ]
