# Generated by Django 6.0.3 on 2026-04-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_wbadvertcampaign_wbadvertstatdaily'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selleraccount',
            name='api_token',
            field=models.TextField(blank=True, default=''),
        ),
    ]
