# Generated by Django 6.0.3 on 2026-04-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_selleraccount_api_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='selleraccount',
            name='sync_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
