# Generated by Django 6.0.3 on 2026-04-20 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_selleraccount_sync_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
