# Generated by Django 6.0.3 on 2026-04-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_order_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_return',
            field=models.BooleanField(default=False),
        ),
    ]
